apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: eshop-frontend
  name: eshop-frontend
spec:
  containers:
  - image: nginx
    name: nginx-container
  - image: redis
    name: redis-container
  - image: memcached
    name: memcached-container
  - image: consul
    name: consul-container



